config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # 'pybo/'로 요청이 들어올 경우 pybo/urls.py로 매핑
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index')
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # ''로 요청이 들어올 경우 views.py 파일의 index 함수 호출
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),
    path('vote/question/<int:question_id>/',
         vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/',
         vote_views.vote_answer, name='vote_answer')
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    # User 모델은 django 앱에서 제공하는 사용자 모델
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    # N:N 관계
    voter = models.ManyToManyField(User, related_name='voter_question')

    # Question 모델 조회시 id값 대신 제목을 표시하도록 매서드 추가
    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='author_answer')
    # Question 모델과 연결 및 삭제연동
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(
        Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(
        Answer, null=True, blank=True, on_delete=models.CASCADE)

pybo/views.py
'''
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question, Answer, Comment
from .forms import QuestionForm, AnswerForm, CommentForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def index(request):
    # URL에서 요청한 페이지 가져옴(default=1)
    page = request.GET.get('page', '1')
    # 질문 목록 내림차순(최신순)으로 조회
    question_list = Question.objects.order_by('-create_date')
    # 페이지당 15개씩 나눔
    paginator = Paginator(question_list, 15)
    # 요청 페이지의 질문 반환
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    # 'pybo/question_list.html' 템플릿 랜더링
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def question_create(request):
    # 요청이 'POST'일 경우
    if request.method == 'POST':
        # request.POST에 전달된 데이터가 각 속성에 자동으로 저장
        form = QuestionForm(request.POST)
        # 데이터가 유효할 경우
        if form.is_valid():
            question = form.save(commit=False)  # 임시 저장
            question.author = request.user
            question.create_date = timezone.now()
            question.save()  # 실제 저장
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # 작성자가 아닐 경우
    if request.user != question.author:
        # non-field error 발생
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    # 요청이 'POST'일 경우(저장)
    if request.method == 'POST':
        # instance(question)값을 request.POST 값으로 대체
        form = QuestionForm(request.POST, instance=question)
        # 유효할 경우 저장(DB 반영)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')


# 로그인되지 않은 상태에서 함수 호출시 'login' 페이지로 이동
@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            # 로그인 계정 저장
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)
    # POST로 전송된 데이터의 'content'를 읽어 Answer 모델에 저장
    # question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    Answer(question=question, content=request.POST.get(
        'content'), create_date=timezone.now()).save()
    return redirect('pybo:detail', question_id=question.id)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)


@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)
'''

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


# 로그인되지 않은 상태에서 함수 호출시 'login' 페이지로 이동
@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            # 로그인 계정 저장
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            # 답변 생성시 책갈피로 이동
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)
    # POST로 전송된 데이터의 'content'를 읽어 Answer 모델에 저장
    # question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    Answer(question=question, content=request.POST.get(
        'content'), create_date=timezone.now()).save()
    return redirect('pybo:detail', question_id=question.id)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Question


def index(request):
    # URL에서 요청한 페이지 가져옴(default=1)
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')
    # 정렬
    if so == 'recommend':
        # 추천 수 내림차순, 최신순
        question_list = Question.objects.annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        # 답변 개수 내림차순, 최신순
        question_list = Question.objects.annotate(num_answer=Count(
            'answer')).order_by('-num_answer', '-create_date')
    else:
        # 질문 목록 내림차순(최신순)으로 조회
        question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(Q(subject__icontains=kw) | Q(content__icontains=kw) | Q(
            author__username__icontains=kw) | Q(answer__author__username__icontains=kw)).distinct()
    # 페이지당 15개씩 나눔
    paginator = Paginator(question_list, 15)
    # 요청 페이지의 질문 반환
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    # 'pybo/question_list.html' 템플릿 랜더링
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question, Answer


@login_required(login_url='common:login')
def vote_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
  <form method="post" class="post-form">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="form-group">
      <label for="content">답변내용</label>
      <!-- 답변 수정 textarea -->
      <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <!-- 제출버튼 -->
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
  <!-- 페이지 타이틀 출력 -->
  <h5 class="border-bottom pb-2">댓글등록하기</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="form-group">
      <label for="content">댓글내용</label>
      <!-- 댓글 입력 textarea -->
      <textarea class="form-control" name="content" id="content" rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <!-- 제출버튼 -->
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}

{% block content %}
<div class="container my-3">
  <!-- non-field error 발생시 -->
  {% if messages %}
  <div class="alert alert-danger my-3" role="alert">
    <!-- 오류 출력 -->
    {% for message in messages %}
    <strong>{{ message.tags }}</strong>
    <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
  </div>
  {% endif %}
  <!-- 질문 제목 출력 -->
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="row my-3">
    <div class="col-1">
      <!-- 추천 수 출력 -->
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ question.voter.count }}</div>
      <!-- 추천 버튼 -->
      <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <div class="col-11">
      <div class="card">
        <div class="card-body">
          <!-- 질문 내용 출력 -->
          <div class="card-text">{{ question.content|mark }}</div>
          <div class="d-flex justify-content-end">
            {% if question.modify_date %}
            <div class="badge badge-light p-2 text-left mx-3">
              <div class="mb-2">modified at</div>
              <div>{{ question.modify_date }}</div>
            </div>
            {% endif %}
            <div class="badge badge-light p-2 text-left">
              <!-- 작성자 출력 -->
              <div class="mb-2">{{ question.author.username }}</div>
              <!-- 질문 일시 출력 -->
              <div>{{ question.create_date }}</div>
            </div>
          </div>
          <!-- 작성자일 경우 -->
          {% if request.user == question.author %}
          <div class="my-3">
            <!-- 질문 수정 버튼 -->
            <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
            <!-- 질문 삭제 버튼 -->
            <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
          </div>
          {% endif %}
          <!-- 만약 댓글이 있을 경우 -->
          {% if question.comment_set.count > 0 %}
          <div class="mt-3">
            {% for comment in question.comment_set.all %}
            <!-- 댓글 책갈피 -->
            <a name="comment_{{ comment.id }}"></a>
            <div class="comment py-2 text-muted">
              <!-- 댓글 출력 -->
              <span style="white-space: pre-line;">{{ comment.content }}</span>
              <!-- 댓글 작성자, 작성일시, 수정일시 출력 -->
              <span>
                - {{ comment.author }}, {{ comment.create_date }}
                {% if comment.modify_date %}
                (수정: {{ comment.modify_date }})
                {% endif %}
              </span>
              <!-- 만약 댓글 작성자일 경우 -->
              {% if request.user == comment.author %}
              <!-- 댓글 수정 버튼 -->
              <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">수정</a>
              <!-- 댓글 삭제 버튼 -->
              <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_question' comment.id %}">삭제</a>
              {% endif %}
            </div>
            {% endfor %}
          </div>
          {% endif %}
          <div>
            <!-- 댓글 추가 버튼 -->
            <a href="{% url 'pybo:comment_create_question' question.id %}" class="small"><small>댓글 추가 ..</small></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- 답변 개수 출력 -->
  <h5 class="border-bottom my-3 py-2">{{ question.answer_set.count}}개의 답변이 있습니다.</h5>
  <!-- 반복문을 돌며 각각의 답변 출력 -->
  {% for answer in question.answer_set.all %}
  <!-- 앵커 추가(책갈피) -->
  <a name="answer_{{ answer.id }}"></a>
  <div class="row my-3">
    <div class="col-1">
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ answer.voter.count }}</div>
      <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}" class="recommend btn btn-sm btn-secondary btn btn-block my-1">추천</a>
    </div>
    <div class="col-11">
      <div class="card">
        <div class="card-body">
          <div class="card-text">{{ answer.content|mark }}</div>
          <div class="d-flex justify-content-end">
            {% if answer.modify_date %}
            <div class="badge badge-light p-2 text-left mx-3">
              <div class="mb-2">modified at</div>
              <div>{{ answer.modify_date }}</div>
            </div>
            {% endif %}
            <div class="badge badge-light p-2 text-left">
              <!-- 작성자 출력 -->
              <div class="mb-2">{{ answer.author.username }}</div>
              <!-- 답변일시 출력 -->
              <div>{{ answer.create_date }}</div>
            </div>
          </div>
          <!-- 작성자일 경우 -->
          {% if request.user == answer.author %}
          <div class="my-3">
            <!-- 답변 수정 버튼 -->
            <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
            <!-- 답변 삭제 버튼 -->
            <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
          </div>
          {% endif %}
          <!-- 만약 댓글이 있을 경우 -->
          {% if answer.comment_set.count > 0 %}
          <div class="mt-3">
            {% for comment in answer.comment_set.all %}
            <!-- 댓글 책갈피 -->
            <a name="comment_{{ comment.id }}"></a>
            <div class="comment py-2 text-muted">
              <!-- 댓글 내용 출력 -->
              <span style="white-space: pre-line;">{{ comment.content }}</span>
              <span>
                <!-- 작성자, 작성일 출력 -->
                - {{ comment.author }}, {{ comment.create_date }}
                <!-- 수정일이 있을 경우 수정일 출력 -->
                {% if comment.modify_date %}
                (수정: {{ comment.modify_date }})
                {% endif %}
              </span>
              <!-- 댓글 작성자일 경우 -->
              {% if request.user == comment.author %}
              <!-- 수정 버튼 -->
              <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">수정</a>
              <!-- 삭제 버튼 -->
              <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
              {% endif %}
            </div>
            {% endfor %}
          </div>
          {% endif %}
          <div>
            <!-- 댓글 추가 버튼 -->
            <a href="{% url 'pybo:comment_create_answer' answer.id %}" class="small"><small>댓글 추가 ..</small></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  <!-- 답변 입력 폼 -->
  <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
    <!-- 실제 웹에서 작성된 데이터가 맞는지 검사 -->
    {% csrf_token %}
    <!-- 폼 오류 발생시 -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      <!-- 각각의 오류 출력 -->
      {% for field in form %}
      {% if field.errors %}
      <strong>{{ field.label }}</strong>
      {{ field.errors }}
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <!-- 답변 입력 textarea -->
    <div class="form-group">
      <!-- 로그인 상태가 아닐 경우 disabled -->
      <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <!-- 답변 제출 버튼 -->
    <input type="submit" value="답변등록" class="btn btn-primary">
  </form>
</div>
{% endblock %}

{%block script %}
<script type="text/javascript">
  // 화면이 로드된 후 함수 자동 호출
  $(document).ready(function(){
    // delete class 태그의 onclick 감지시
    $(".delete").on('click', function(){
      // confirm이 true일 경우
      if(confirm("정말로 삭제하시겠습니까?")){
        // href=data-uri값(즉, data-uri url 호출)
        location.href = $(this).data('uri');
      }
    })
    $(".recommend").on('click', function(){
      if(confirm("정말로 추천하시겠습니까?")){
        location.href = $(this).data('uri');
      }
    })
  })
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문등록</h5>
  <!-- action을 지정하지 않아도 폼을 호출한 'pybo:question_create'로 자동 매핑 -->
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- QuestionForm에서 정의한 폼 자동 생성 -->
    <!-- {{ form.as_p }} -->
    <!-- 폼 오류 있을 경우 -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      <!-- 각 오류 표시 -->
      {% for field in form %}
      {% if field.errors %}
      <strong>{{ field.label }}</strong>
      {{ field.errors }}
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <div class="form-group">
      <!-- 질문 제목 입력 구역 -->
      <label for="subject">제목</label>
      <!-- 입력값 유지 -->
      <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
      <!-- 질문 내용 입력 구역 -->
      <label for="content">내용</label>
      <!-- 입력값 유지 -->
      <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <!-- 제출버튼 -->
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}